sudo: false
language: ruby
rvm:
  - 2.3.0
before_install: gem install bundler -v 1.12.5

before_script:
  - bundle exec danger

branches:
  - only:
    - master

script:
  - if [[ $(git rev-parse --abbrev-ref HEAD) != "master" && -z $(git diff origin/master -- lib/caseflow/version.rb) ]]; then
      echo "Update version number when updating caseflow commons (lib/caseflow/version.rb)";
      exit 1;
    fi
  - bundle exec rake

services:
  - redis-server
