sudo: false
language: ruby
rvm:
  - 2.5.3
#before_install: gem install bundler -v 1.17
cache: bundler --without development

before_script:
  - bundle exec danger

branches:
  - only:
    - master

script:
  - bundle exec rake

services:
  - redis-server
