sudo: false
language: ruby
rvm:
  - 2.3.0
before_install: gem install bundler -v 1.12.5

before_script:
  - bundle exec danger

branches:
  - only:
    - master

script:
  - sudo service ntp stop
  - sudo ntpd -gq
  - sudo service ntp start
  - bundle exec rake

services:
  - redis-server
